### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by mirca** [dppalomar/riskParityPortfolio#1]
As mentioned by @dppalomar, we should:
- [ ]  allow users to specify box constraints for `w`, i.e., `lb <= w <= ub`.
- [x] include the preference function, typically the expected return. 
- [ ] add Roncalli's square-root formulation using the Newton method
- [ ] add turnover constraint
- [x] implement the Newton method with backtracking
- [x] implement the coordinate descent method
- [x] add support for the variance term
- [x] expand the set of unit tests
- [ ] add the pdf format of the vignette
